<?php $config = $this->getConfigJson(); ?>
<?php if($config['customer_garage_uri'] && !$config['customer_garage_is_empty']):?>
	<div class="selected_car_block">
		<strong><?php echo sprintf(__('That fit your %s'), ucwords($config['customer_garage_uri_name'])); ?></strong>
	</div>
	<style>
	 h1.page-title { margin-bottom: 0px !important;}
     div.selected_car_block { margin: 15px 0 15px 0;}	 
	</style>
<?php endif; ?>