<?php
use Wolf\Filter\Block\Navigation as B;
use Wolf\Filter\Customer as WC;
$b = $block; /** @var B $block */ /** @var B $b */
$config = $b->getConfigJson();
list($selectedCarContStyle, $selectedCarContStyle1) =
	!df_action_is('catalog_category_view', 'catalogsearch_result_index', 'cms_noroute_index')
	? ['', ''] : ['style="display: block;"', 'style="display: none;"']
;
?>
<div class='block' style='margin-bottom: 0; min-height: 40px;'>
	<div class='garage-selected-car-cont' <?= $selectedCarContStyle; ?>>
		Selected Car: &nbsp;&nbsp;
		<?php if ($config['customer_garage_uri'] && WC::garage()) {?>
			<a
				class="garage-selected-car-link"
				href="<?= $config['customer_garage_uri']; ?>"
				style="text-transform: capitalize;"
			><?= $config['customer_garage_uri_name'] ?></a>
		<?php } else {?>
			<a class="garage-selected-car-link" href="#"><?= __('No Car Selected'); ?></a>
		<?php } ?>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<button class="btn-link change-car-btn">Change Car</button>
	</div>
	<div class="block nav-categoryfilters garage-cont" <?= $selectedCarContStyle1; ?>>
		<div class="block-title title-row">
			<div><strong><span><?= $b['title'] ?></span></strong></div>
			<div><div class="loading-message"><?= $b['loading_message'] ?: 'Loading...' ?></div></div>
		</div>
		<div style='garage-block'>
			<div class='garage-block-cars'>
				<form action='' class='row change-car-form' id='change-car' method='post' name='change-car-form'
				></form>
			</div>
			<div class="garage-block-filters">
				<form action='' class='row category-form' id='add-new-car' method='post' name='category-form'>
					<div class='block-content row' id='cd-<?= $b->getNameInLayout() ?>'>
						<?= $b->hDropdowns() ?>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<div class='clearfix'></div>
<script type='text/javascript'>
	requirejs(['jquery', 'categoryFilter'], function($) {
		$('#cd-<?= $b->getNameInLayout() ?>').categoryfilter(<?= df_json_encode([
			'labelsAreInside' => $b->labelsAreInside()
			,'levels' => $b['levels']
			,'nameInLayout' => $b->getNameInLayout()
			,'url' => df_url('categoryfinder/index/change')
		]) ?>);
	});
</script>